name: Run Tests

on:
  push:
    branches:
      - master
    tags:
      - v*

  pull_request:
    branches: 
      - master

jobs:
  test-build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Test build
        run: go test -timeout 120s -v;